import { createFileRoute } from "@tanstack/react-router";
import { Award } from "lucide-react";
import { PageIntro, SectionLabel } from "@/components/portfolio-shell";

export const Route = createFileRoute("/achievements")({ head:()=>({meta:[{title:"Achievements — Deepalakshmi S"},{name:"description",content:"Awards, milestones and certifications earned by Deepalakshmi S."},{property:"og:title",content:"Achievements — Deepalakshmi S"},{property:"og:description",content:"A record of hackathons, recognition, student leadership and learning."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component:Achievements });
const milestones=[
  ["2025","CREATEATHON","First Prize"],["2025","SELF-E Hackathon","Finalist — 7th place among 100 teams"],["2025","OSSOME HACKS 3.0 · SRMIST","Participant"],["2025","National Building Case Study Competition","Participant"],["2026","Student Partner — Internshala","Coimbatore · Promoted internship opportunities and connected students with relevant career programs."],
];
const certificates=[
  ["2025","C Programming Basics · Internet of Things","Simplilearn"],["2025","HTML5, CSS, JavaScript","Infosys Springboard"],["2025","C Programming","Udemy"],["2026","Software Engineer · Design Developer","HackerRank"],["2026","AWS with AI","Unstop"],
];
function Achievements(){return <><PageIntro eyebrow="Record / Milestones" title={<>Progress,<br/>milestones &<br/><span className="text-primary">recognition.</span></>}/><section className="mx-auto max-w-[1440px] px-5 py-20 lg:px-10 lg:py-32"><SectionLabel index="01">Milestones</SectionLabel><div>{milestones.map(([year,title,detail],i)=><article key={title} className="group grid gap-4 border-t border-border py-8 md:grid-cols-[120px_1fr_1fr]"><span className="font-mono text-[10px] text-primary">{year}</span><h2 className="font-display text-2xl uppercase md:text-3xl">{title}</h2><div className="flex items-start gap-3 text-muted-foreground"><Award className="mt-1 size-4 shrink-0 text-champagne"/><p className="leading-7">{detail}</p><span className="ml-auto font-mono text-[9px]">0{i+1}</span></div></article>)}</div></section><section className="border-t border-border bg-secondary"><div className="mx-auto max-w-[1440px] px-5 py-20 lg:px-10 lg:py-28"><SectionLabel index="02">Certifications</SectionLabel><div className="grid gap-px bg-border md:grid-cols-2">{certificates.map(([year,title,issuer])=><article key={title} className="bg-background p-7 lg:p-9"><p className="font-mono text-[9px] text-primary">{year}</p><h2 className="mt-8 font-display text-2xl">{title}</h2><p className="mt-3 text-sm text-muted-foreground">{issuer}</p></article>)}</div></div></section></>}