import { createFileRoute } from "@tanstack/react-router";
import { Braces, Github, Linkedin } from "lucide-react";
import { ExternalArrow, PageIntro } from "@/components/portfolio-shell";
import { socialLinks } from "@/lib/portfolio-data";

export const Route = createFileRoute("/coding")({head:()=>({meta:[{title:"Coding Profiles — Deepalakshmi S"},{name:"description",content:"Explore Deepalakshmi S on LeetCode, GitHub and LinkedIn."},{property:"og:title",content:"Where Deepalakshmi Codes & Builds"},{property:"og:description",content:"Coding practice, technical projects and professional presence."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Coding});
const cards=[
  {n:"01",name:"LeetCode",user:"@deepalakshmi_sakthiraman",href:socialLinks.leetcode,copy:"Practicing data structures and algorithms through problem solving.",Icon:Braces,stats:["Max Rating · 150","Global Rank · 242,138","Problems Solved · 460+"]},
  {n:"02",name:"GitHub",user:"@deepalakshmi-ssr",href:socialLinks.github,copy:"Projects, development work and technical builds.",Icon:Github,stats:[]},
  {n:"03",name:"LinkedIn",user:"@deepalakshmi-sakthisabariraman",href:socialLinks.linkedin,copy:"Professional updates, achievements, internships and collaborations.",Icon:Linkedin,stats:[]},
];
function Coding(){return <><PageIntro eyebrow="Profiles / Practice" title={<>Where I code,<br/>ship & solve<br/><span className="text-primary">problems.</span></>} copy="A quick look at my coding practice, open-source work and professional presence."/><section className="mx-auto grid max-w-[1440px] gap-px bg-border px-5 py-20 lg:grid-cols-3 lg:px-10 lg:py-32">{cards.map(({n,name,user,href,copy,Icon,stats})=><a key={name} href={href} target="_blank" rel="noreferrer" className="group flex min-h-[430px] flex-col bg-background p-7 transition-colors hover:bg-secondary lg:p-9"><div className="flex items-center justify-between"><span className="font-mono text-[10px] text-primary">{n}</span><Icon className="size-5"/></div><div className="mt-auto"><h2 className="font-display text-4xl uppercase">{name}</h2><p className="mt-2 break-all font-mono text-[9px] text-muted-foreground">{user}</p><p className="mt-7 leading-7 text-muted-foreground">{copy}</p>{stats.length>0&&<div className="mt-7 space-y-2 border-t border-border pt-5">{stats.map(s=><p className="font-mono text-[9px] uppercase" key={s}>{s}</p>)}</div>}<div className="mt-8 flex items-center gap-2 text-sm font-medium uppercase">Open profile <ExternalArrow/></div></div></a>)}</section></>}