import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { PageIntro, SectionLabel } from "@/components/portfolio-shell";
import { projects } from "@/lib/portfolio-data";

const details = {
  mova: { problem: "Wheelchair users can encounter uneven terrain, potholes, slopes, obstacles, inaccessible routes and uncertain mobility conditions.", solution: "MOVA aims to provide intelligent assistance without replacing the user’s control.", features: ["Terrain Detection","Obstacle Awareness","Wheelchair-Friendly Navigation","Mobility Risk Analysis","Sensor-Based Awareness","Computer Vision","Accessibility Intelligence"], how: ["Camera / Sensors","Data Processing","Terrain & Obstacle Analysis","Risk Assessment","User Warning / Assistance"], tech: "A modular direction combining camera input, environmental sensors, computer vision, navigation logic and clear user feedback.", future: "The system is being developed with safety and user control as priorities. Future capabilities remain exploratory until tested and implemented." },
  hirereadyai: { problem: "Candidate screening and placement preparation can become fragmented across interviews, coding tests and performance records.", solution: "An intelligent placement system that brings AI-based interviews, coding assessments and analytics into one evaluation experience.", features: ["AI Interview","Coding Assessment","Analytics Dashboard","Candidate Evaluation","Student Performance Tracking"], how: ["Candidate Profile","AI Interview","Coding Assessment","Evaluation","Analytics Dashboard"], tech: "A responsive product experience designed around structured assessments, clear evaluation signals and useful progress visibility.", future: "Future scope can deepen evaluation workflows and insights while retaining transparent, responsible assessment." },
  agrimate: { problem: "Farmers need practical access to changing weather, soil, crop, pest and market information, often across language and literacy barriers.", solution: "AGRIMATE brings essential farming guidance into one responsive web application with accessible voice interaction.", features: ["Weather Forecasting","Soil Testing","Crop Recommendations","Pest Alerts","Market Prices","AI Voice Assistant","Five-Language Interaction"], how: ["Voice or Touch Input","Speech-to-Text","Guidance Processing","Visual Response","Audio Output"], tech: "The voice assistant supports five languages with speech-to-text, audio output and speech visualization to improve access for rural users.", future: "Intended to make agricultural information easier to reach; future scope can expand guidance while validating information quality and local relevance." },
} as const;

export const Route = createFileRoute("/projects/$slug")({
  loader: ({params}) => { const project = projects.find(p=>p.slug===params.slug); if(!project || !(params.slug in details)) throw notFound(); return { project, detail: details[params.slug as keyof typeof details] }; },
  head: ({loaderData}) => ({ meta: loaderData ? [ { title: `${loaderData.project.name} — Deepalakshmi S` }, { name:"description",content:loaderData.project.description }, { property:"og:title",content:`${loaderData.project.name} — ${loaderData.project.label}` }, { property:"og:description",content:loaderData.project.description }, { property:"og:type",content:"article" }, { name:"twitter:card",content:"summary_large_image" } ] : [{title:"Project not found"},{name:"robots",content:"noindex"}] }), component: ProjectDetail,
});
function ProjectDetail(){ const {project,detail}=Route.useLoaderData(); return <><PageIntro eyebrow={`${project.number} / ${project.category}`} title={<>{project.name}<br/><span className="text-primary">{project.label}</span></>} copy={project.description}/><section className="mx-auto max-w-[1440px] px-5 py-12 lg:px-10 lg:py-20"><div className="image-frame overflow-hidden bg-muted"><img src={project.image} alt={project.alt} className="aspect-[16/7] w-full object-cover"/></div><div className="mt-5 flex justify-between font-mono text-[9px] uppercase text-muted-foreground"><span>{project.status}</span><span>Deepalakshmi S · Project</span></div></section><section className="mx-auto max-w-[1440px] px-5 pb-24 lg:px-10 lg:pb-32"><div className="grid gap-12 lg:grid-cols-2"><Story index="01" title="The problem" text={detail.problem}/><Story index="02" title="The solution" text={detail.solution}/></div><div className="mt-20"><SectionLabel index="03">How it works</SectionLabel><div className="grid gap-3 md:grid-cols-5">{detail.how.map((x,i)=><div className="border border-border bg-secondary p-5" key={x}><span className="font-mono text-[9px] text-primary">0{i+1}</span><p className="mt-10 text-sm font-medium">{x}</p></div>)}</div></div><div className="mt-20 grid gap-16 lg:grid-cols-2"><div><SectionLabel index="04">Key features</SectionLabel><ul>{detail.features.map(x=><li key={x} className="border-b border-border py-4 text-lg">{x}</li>)}</ul></div><div><SectionLabel index="05">Technology direction</SectionLabel><p className="leading-8 text-muted-foreground">{detail.tech}</p><h3 className="mt-12 font-display text-3xl">Future scope</h3><p className="mt-5 leading-8 text-muted-foreground">{detail.future}</p></div></div><Link to="/projects" className="mt-20 inline-flex items-center gap-2 font-mono text-[10px] uppercase"><ArrowLeft className="size-4"/> All projects <ArrowUpRight className="size-4"/></Link></section></> }
function Story({index,title,text}:{index:string;title:string;text:string}){return <article className="border-t border-border pt-5"><span className="font-mono text-[9px] text-primary">{index}</span><h2 className="mt-8 font-display text-4xl uppercase">{title}</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">{text}</p></article>}